export const SIMULATION_CONFIG = {
  INITIAL_STOCK: 100,
  PACKET_POOL_SIZE: 10,
  LOG_Limit: 50,
};

export const TIMINGS = {
  MARKETPLACE_LATENCY_MS: 800,
  MASTER_SYNC_DURATION_MS: 2000,
  PACKET_FAIL_RETRY_MS: 2000,
  GHOST_STRATEGY_DELAY_MS: 1500,
};

export const THRESHOLDS = {
  BUFFER_PERCENT_MAX: 30,
  SYNC_SENSITIVITY_REL_MAX: 15,
  SYNC_SENSITIVITY_ABS_MAX: 10,
};
